### ISSUE TITLE
CRAN issues

### ISSUE THREAD

**Issue by Tabima** [grunwaldlab/effectR#10]
After attempts to submit the package to CRAN, I received an email with a problem in CRAN:

```
Found the following (possibly) invalid URLs:
 URL: https://cran.r-project.org/web/packages/seqinr/seqinr.pdf
   From: inst/doc/effectR.html
   Status: 200
   Message: OK
   CRAN URL not in canonical form
 The canonical URL of the CRAN page for a package is
   https://CRAN.R-project.org/package=pkgname
```

I *think* I solved the problem, but that might just mean that I'm omitting something or that there could be more potential problems and I really don't want to get banned from CRAN.

I was wondering if @knausb, @zkamvar and @zachary-foster could help me review the package real quick and check that its fine for CRAN. So far, I've succesfully:

- Build the package locally and via winbuilder
- Passed the tests and checks locally
- Installed and passed on Travis-CI (https://travis-ci.com/Tabima/effectR/jobs/105758494)
- Build, installed and used the package in Windows, MacOSX and Linux (Ubuntu and CentOS)

Am I missing something else?

**Comment by zachary-foster** [comment]
Wahoo! Nice job!

**Comment by knausb** [comment]
Yay! Congrats!

**Comment by zkamvar** [comment]
CRAN-gratulations!

**Comment by knausb** [comment]
Oh no! I didn't realize solaris was back up and running. You passed, whew!
