### ISSUE TITLE
Issue related to HMM threshold 

### ISSUE THREAD

**Issue by Ramakrishna0007** [grunwaldlab/effectR#17]
good morning sir... this is Ramakrishna...
The high number of effector proteins predicted in the HMM step is a result of the low thresholds used by our package in order to obtain as many candidate effectors as possible
sir...... what is the threshold you have used in this package...
low threshold means what?
and one more is how did you separate the non-redundant and redundant candidates.

**Comment by Tabima** [comment]
Hi,

Both minimum threshold value and detection of redundant candidates are explained in the effectR paper and the manual of effectR. 

In summary: 

- T=0 as threshold for HMMER 
- `effector.summary()` to remove redundant effectors.
