### ISSUE TITLE
Regarding regex pattern 

### ISSUE THREAD

**Issue by Ramakrishna0007** [grunwaldlab/effectR#20]
good evening sir...
this is Ramakrishna.
"^\\w{10,40}\\w{1,96}R\\wLR\\w{1,40}eer" this regex pattern is searching for proteins
{1,96}R\\wLR == only having RXLR  motifs separately and
{1,40}eer == having EER motifs separately.. 

Sir, actually I need a pattern search for  proteins having only "^\\w{10,40}\\w{1,96}R\\wLR\\w{1,40}eer" this pattern and not separately, i don't want only RXLR and only EER having proteins.
I tried with subsetting complete motifs form data frame, even though I am getting proteins with 
only RXLR and only EER and both.

**Comment by Tabima** [comment]
Hi,
I don't seem to understand your question, sorry.

You want only the proteins with both RxLR and EER proteins? If so then run the pipeline, and at the `effector.summary` step select only the proteins that show "Complete" in the motif table.
